// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_thresholds_cpp
NumericVector compute_thresholds_cpp(NumericVector d1, int max_level, double alpha, double beta);
RcppExport SEXP _rLifting_compute_thresholds_cpp(SEXP d1SEXP, SEXP max_levelSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< int >::type max_level(max_levelSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_thresholds_cpp(d1, max_level, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// run_turbo_batch
NumericVector run_turbo_batch(NumericVector signal, List steps, NumericVector norm, int window_size, double alpha, double beta, std::string method, int ext_mode, int update_freq);
RcppExport SEXP _rLifting_run_turbo_batch(SEXP signalSEXP, SEXP stepsSEXP, SEXP normSEXP, SEXP window_sizeSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP methodSEXP, SEXP ext_modeSEXP, SEXP update_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< List >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type norm(normSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type ext_mode(ext_modeSEXP);
    Rcpp::traits::input_parameter< int >::type update_freq(update_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(run_turbo_batch(signal, steps, norm, window_size, alpha, beta, method, ext_mode, update_freq));
    return rcpp_result_gen;
END_RCPP
}
// ilwt_cpp
NumericVector ilwt_cpp(List coeffs_list, List steps, NumericVector norm, int levels, int ext_mode, int original_len);
RcppExport SEXP _rLifting_ilwt_cpp(SEXP coeffs_listSEXP, SEXP stepsSEXP, SEXP normSEXP, SEXP levelsSEXP, SEXP ext_modeSEXP, SEXP original_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type coeffs_list(coeffs_listSEXP);
    Rcpp::traits::input_parameter< List >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type norm(normSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< int >::type ext_mode(ext_modeSEXP);
    Rcpp::traits::input_parameter< int >::type original_len(original_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(ilwt_cpp(coeffs_list, steps, norm, levels, ext_mode, original_len));
    return rcpp_result_gen;
END_RCPP
}
// lwt_cpp
List lwt_cpp(NumericVector signal, List steps, NumericVector norm, int levels, int ext_mode);
RcppExport SEXP _rLifting_lwt_cpp(SEXP signalSEXP, SEXP stepsSEXP, SEXP normSEXP, SEXP levelsSEXP, SEXP ext_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< List >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type norm(normSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< int >::type ext_mode(ext_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(lwt_cpp(signal, steps, norm, levels, ext_mode));
    return rcpp_result_gen;
END_RCPP
}
// run_causal_batch_cpp
NumericVector run_causal_batch_cpp(NumericVector signal, List steps, NumericVector norm, int levels, int window_size, double alpha, double beta, std::string method, int ext_mode, int update_freq);
RcppExport SEXP _rLifting_run_causal_batch_cpp(SEXP signalSEXP, SEXP stepsSEXP, SEXP normSEXP, SEXP levelsSEXP, SEXP window_sizeSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP methodSEXP, SEXP ext_modeSEXP, SEXP update_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< List >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type norm(normSEXP);
    Rcpp::traits::input_parameter< int >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type ext_mode(ext_modeSEXP);
    Rcpp::traits::input_parameter< int >::type update_freq(update_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(run_causal_batch_cpp(signal, steps, norm, levels, window_size, alpha, beta, method, ext_mode, update_freq));
    return rcpp_result_gen;
END_RCPP
}
// threshold_hard_cpp
NumericVector threshold_hard_cpp(NumericVector x, double lambda);
RcppExport SEXP _rLifting_threshold_hard_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(threshold_hard_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// threshold_soft_cpp
NumericVector threshold_soft_cpp(NumericVector x, double lambda);
RcppExport SEXP _rLifting_threshold_soft_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(threshold_soft_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// threshold_semisoft_cpp
NumericVector threshold_semisoft_cpp(NumericVector x, double lambda);
RcppExport SEXP _rLifting_threshold_semisoft_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(threshold_semisoft_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// apply_filter_cpp
NumericVector apply_filter_cpp(NumericVector x, NumericVector coeffs, int start_idx, int ext_mode);
RcppExport SEXP _rLifting_apply_filter_cpp(SEXP xSEXP, SEXP coeffsSEXP, SEXP start_idxSEXP, SEXP ext_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< int >::type start_idx(start_idxSEXP);
    Rcpp::traits::input_parameter< int >::type ext_mode(ext_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_filter_cpp(x, coeffs, start_idx, ext_mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rLifting_compute_thresholds_cpp", (DL_FUNC) &_rLifting_compute_thresholds_cpp, 4},
    {"_rLifting_run_turbo_batch", (DL_FUNC) &_rLifting_run_turbo_batch, 9},
    {"_rLifting_ilwt_cpp", (DL_FUNC) &_rLifting_ilwt_cpp, 6},
    {"_rLifting_lwt_cpp", (DL_FUNC) &_rLifting_lwt_cpp, 5},
    {"_rLifting_run_causal_batch_cpp", (DL_FUNC) &_rLifting_run_causal_batch_cpp, 10},
    {"_rLifting_threshold_hard_cpp", (DL_FUNC) &_rLifting_threshold_hard_cpp, 2},
    {"_rLifting_threshold_soft_cpp", (DL_FUNC) &_rLifting_threshold_soft_cpp, 2},
    {"_rLifting_threshold_semisoft_cpp", (DL_FUNC) &_rLifting_threshold_semisoft_cpp, 2},
    {"_rLifting_apply_filter_cpp", (DL_FUNC) &_rLifting_apply_filter_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rLifting(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
