# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper: mediana absoluta (MAD) em C++
NULL

compute_thresholds_cpp <- function(d1, max_level, alpha, beta) {
    .Call(`_rLifting_compute_thresholds_cpp`, d1, max_level, alpha, beta)
}

create_engine_cpp <- function(steps, norm, levels, window_size, ext_mode) {
    .Call(`_rLifting_create_engine_cpp`, steps, norm, levels, window_size, ext_mode)
}

process_sample_cpp <- function(engine_ptr, new_sample, alpha, beta, method, update_freq, step_iter) {
    .Call(`_rLifting_process_sample_cpp`, engine_ptr, new_sample, alpha, beta, method, update_freq, step_iter)
}

run_causal_batch_cpp <- function(signal, steps, norm, levels, window_size, alpha, beta, method, ext_mode, update_freq) {
    .Call(`_rLifting_run_causal_batch_cpp`, signal, steps, norm, levels, window_size, alpha, beta, method, ext_mode, update_freq)
}

#' Core ILWT (C++)
NULL

ilwt_cpp <- function(coeffs_list, steps, norm, levels, ext_mode, original_len) {
    .Call(`_rLifting_ilwt_cpp`, coeffs_list, steps, norm, levels, ext_mode, original_len)
}

#' Core LWT (C++)
NULL

lwt_cpp <- function(signal, steps, norm, levels, ext_mode) {
    .Call(`_rLifting_lwt_cpp`, signal, steps, norm, levels, ext_mode)
}

#' Unified offline denoising
NULL

denoise_offline_cpp <- function(signal, steps, norm, levels, alpha, beta, method, ext_mode) {
    .Call(`_rLifting_denoise_offline_cpp`, signal, steps, norm, levels, alpha, beta, method, ext_mode)
}

#' Hard Thresholding (C++)
NULL

threshold_hard_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_hard_cpp`, x, lambda)
}

threshold_soft_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_soft_cpp`, x, lambda)
}

threshold_semisoft_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_semisoft_cpp`, x, lambda)
}

#' Aplica filtro via convolucao (Core C++)
NULL

apply_filter_cpp <- function(x, coeffs, start_idx, ext_mode) {
    .Call(`_rLifting_apply_filter_cpp`, x, coeffs, start_idx, ext_mode)
}

