# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper: Mediana Absoluta (MAD) em C++
NULL

compute_thresholds_cpp <- function(d1, max_level, alpha, beta) {
    .Call(`_rLifting_compute_thresholds_cpp`, d1, max_level, alpha, beta)
}

#' Turbo Causal Batch (Full Implementation)
NULL

run_turbo_batch <- function(signal, steps, norm, window_size, alpha, beta, method, ext_mode, update_freq) {
    .Call(`_rLifting_run_turbo_batch`, signal, steps, norm, window_size, alpha, beta, method, ext_mode, update_freq)
}

#' Core ILWT (C++)
NULL

ilwt_cpp <- function(coeffs_list, steps, norm, levels, ext_mode, original_len) {
    .Call(`_rLifting_ilwt_cpp`, coeffs_list, steps, norm, levels, ext_mode, original_len)
}

#' Core LWT (C++)
NULL

lwt_cpp <- function(signal, steps, norm, levels, ext_mode) {
    .Call(`_rLifting_lwt_cpp`, signal, steps, norm, levels, ext_mode)
}

#' Causal Denoising Batch (C++ Optimized Ring Buffer)
NULL

run_causal_batch_cpp <- function(signal, steps, norm, levels, window_size, alpha, beta, method, ext_mode, update_freq = 1L) {
    .Call(`_rLifting_run_causal_batch_cpp`, signal, steps, norm, levels, window_size, alpha, beta, method, ext_mode, update_freq)
}

#' Hard Thresholding (C++)
NULL

threshold_hard_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_hard_cpp`, x, lambda)
}

threshold_soft_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_soft_cpp`, x, lambda)
}

threshold_semisoft_cpp <- function(x, lambda) {
    .Call(`_rLifting_threshold_semisoft_cpp`, x, lambda)
}

#' Aplica filtro via convolucao (Core C++)
NULL

apply_filter_cpp <- function(x, coeffs, start_idx, ext_mode) {
    .Call(`_rLifting_apply_filter_cpp`, x, coeffs, start_idx, ext_mode)
}

